services:
  - type: web
    name: canteen-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_NAME
        fromDatabase:
          name: canteen-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: canteen-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: canteen-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: canteen-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: canteen-db
          property: port
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d

databases:
  - name: canteen-db
    databaseName: canteen
    user: canteen
